name: PokeApp

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        
      - name: Install ğŸ”§
        run: npm install


      - name: start
        run: npm start


      - name: test
        run: npm test


      - name: Build ğŸ—ï¸
        run: npm run build


      - name: eject
        run: npm run eject

     
    
